K=20
Base=3
BR=10
Num_of_nodes=10
time_of_simulation=60
Num_of_users=5
Num_of_jobs_per_sec=6
Execution_time=10
fog_nodes=[]
global_queue=[]
cnt=0
dropped_tasks=[]
completed_tasks=[]
num = 1
Cost=0
total_tasks_generated = 0
total_successful_tasks = 0
tasks_dropped = 0
active = 0
time_window = 10
tasks_window = 5
total_time = 0
failure_count = 0
flag = 0
jobs_data = []